FROM microsoft/dotnet:2.1-aspnetcore-runtime-nanoserver-1709 AS base
WORKDIR /app
EXPOSE 80

FROM microsoft/dotnet:2.1-sdk-nanoserver-1709 AS build
WORKDIR /src
COPY Argento.ReportingService/Argento.ReportingService.csproj Argento.ReportingService/
RUN dotnet restore Argento.ReportingService/Argento.ReportingService.csproj
COPY . .
WORKDIR /src/Argento.ReportingService
RUN dotnet build Argento.ReportingService.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Argento.ReportingService.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Argento.ReportingService.dll"]
